os: linux
group: stable
sudo: required
dist: bionic
services:
  - docker
language: generic
python:
  - "2.7"
env:
  global:
    - ROSDEP_SKIP_KEYS=raspimouse_ros_2
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=xenial
    - ROS_DISTRO=melodic ROS_REPO=ros UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=bionic
before_install:
    - git clone https://github.com/ryuichiueda/raspimouse_ros_2
install:
    - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
    - source .ci_config/travis.sh
